/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/formula': RouteRecordInfo<'/formula', '/formula', Record<never, never>, Record<never, never>>,
    '/practice': RouteRecordInfo<'/practice', '/practice', Record<never, never>, Record<never, never>>,
    '/search-results': RouteRecordInfo<'/search-results', '/search-results', Record<never, never>, Record<never, never>>,
    '/units/analytical-applications-differentiation': RouteRecordInfo<'/units/analytical-applications-differentiation', '/units/analytical-applications-differentiation', Record<never, never>, Record<never, never>>,
    '/units/applications-integration': RouteRecordInfo<'/units/applications-integration', '/units/applications-integration', Record<never, never>, Record<never, never>>,
    '/units/contextual-applications-differentiation': RouteRecordInfo<'/units/contextual-applications-differentiation', '/units/contextual-applications-differentiation', Record<never, never>, Record<never, never>>,
    '/units/differential-equations': RouteRecordInfo<'/units/differential-equations', '/units/differential-equations', Record<never, never>, Record<never, never>>,
    '/units/differentiation-composite-implicit-inverse': RouteRecordInfo<'/units/differentiation-composite-implicit-inverse', '/units/differentiation-composite-implicit-inverse', Record<never, never>, Record<never, never>>,
    '/units/differentiation-definition-properties': RouteRecordInfo<'/units/differentiation-definition-properties', '/units/differentiation-definition-properties', Record<never, never>, Record<never, never>>,
    '/units/integration-accumulation-change': RouteRecordInfo<'/units/integration-accumulation-change', '/units/integration-accumulation-change', Record<never, never>, Record<never, never>>,
    '/units/limits': RouteRecordInfo<'/units/limits', '/units/limits', Record<never, never>, Record<never, never>>,
  }
}
